version: "3.9"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    ports:
      - "9001:9000"
    restart: always
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    links:
      - mariadb
